_name_or_path:
    value: vinai/PhoWhisper-large
_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": train/grad_norm
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 35
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
                - 103
            "3":
                - 7
                - 13
                - 16
                - 19
                - 55
                - 66
            "4": 3.10.15
            "5": 0.20.1
            "6": 4.52.4
            "9":
                "1": transformers_trainer
            "12": 0.20.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_dropout:
    value: 0
activation_function:
    value: gelu
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
apply_spec_augment:
    value: false
architectures:
    value:
        - WhisperForConditionalGeneration
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value:
        - 220
        - 50257
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 50257
chunk_size_feed_forward:
    value: 0
classifier_proj_size:
    value: 256
cross_attention_hidden_size:
    value: null
d_model:
    value: 1280
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset:
    value: namespace(name='nguyendv02/ViMD_Dataset', cache_dir='./cache', sampling_rate=16000, regions=['All', 'Central', 'South', 'North'])
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_attention_heads:
    value: 20
decoder_ffn_dim:
    value: 5120
decoder_layerdrop:
    value: 0
decoder_layers:
    value: 32
decoder_start_token_id:
    value: 50258
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dropout:
    value: 0
early_stopping:
    value: false
encoder_attention_heads:
    value: 20
encoder_ffn_dim:
    value: 5120
encoder_layerdrop:
    value: 0
encoder_layers:
    value: 32
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 50257
eval:
    value: namespace(compute_metrics=True, eval_on_train=False, eval_on_test=True, eval_on_dev=True, eval_on_all=False, eval_on_all_regions=True, regions=['All', 'Central', 'South', 'North'], region='south', test_split='test', dev_split='dev', train_split='train', all_split='all')
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 100
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_decoder_ids:
    value:
        - - 1
          - 50278
        - - 2
          - 50359
        - - 3
          - 50363
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generation_config:
    value: null
generation_max_length:
    value: null
generation_num_beams:
    value: null
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: minhtien2405/phowhisper-large-south-vi
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
init_std:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: true
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 1e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging:
    value: namespace(log_dir='./logs', log_file='phowhisper_large_vi_south_v0.log')
logging_dir:
    value: ./logs/phowhisper-large-south-vi/runs/Jun29_05-25-19_vovinam-ai-v0-20250625-203146
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lora:
    value: namespace(r=32, lora_alpha=64, target_modules=['q_proj', 'v_proj'], lora_dropout=0.05, bias='none')
lr_scheduler_type:
    value: linear
mask_feature_length:
    value: 10
mask_feature_min_masks:
    value: 0
mask_feature_prob:
    value: 0
mask_time_length:
    value: 10
mask_time_min_masks:
    value: 2
mask_time_prob:
    value: 0.05
max_grad_norm:
    value: 1
max_length:
    value: 448
max_source_positions:
    value: 1500
max_steps:
    value: -1
max_target_positions:
    value: 448
median_filter_width:
    value: 7
metric_for_best_model:
    value: wer
min_length:
    value: 0
model:
    value: namespace(model_id='vinai/PhoWhisper-large', language='vi', task='transcribe', quantization=namespace(load_in_4bit=True, bnb_4bit_compute_dtype='float16', bnb_4bit_use_double_quant=True, bnb_4bit_quant_type='nf4'), device='cuda')
model/num_parameters:
    value: 1559033600
model_type:
    value: whisper
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_mel_bins:
    value: 80
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adamw_bnb_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./logs/phowhisper-large-south-vi
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 50257
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: vinai/PhoWhisper-large
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 64
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 32
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - q_proj
                - v_proj
            task_type: null
            trainable_token_indices: null
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
predict_with_generate:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: true
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: float16
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - mlflow
        - tensorboard
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: ./logs/phowhisper-large-south-vi
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 3
scale_embedding:
    value: false
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sortish_sampler:
    value: false
suppress_tokens:
    value: []
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
training:
    value: namespace(output_dir='./logs/phowhisper-large-south-vi', eval_output_dir='./outputs/phowhisper-large-south-vi', per_device_train_batch_size=4, gradient_accumulation_steps=8, learning_rate='1e-5', warmup_steps=50, save_steps=100, save_total_limit=3, logging_steps=50, fp16=True, optim='adamw_bnb_8bit', eval_strategy='steps', eval_steps=100, per_device_eval_batch_size=4, metric_for_best_model='wer', greater_is_better=False, load_best_model_at_end=True, save_strategy='steps', hub_model_id='minhtien2405/phowhisper-large-south-vi')
transformers_version:
    value: 4.52.4
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_weighted_layer_sum:
    value: false
vocab_size:
    value: 51865
wandb:
    value: namespace(project='PhoWhisper_ViMD', run_name='phowhisper_finetune_south')
warmup_ratio:
    value: 0
warmup_steps:
    value: 50
weight_decay:
    value: 0
