model:
  model_id: "vinai/PhoWhisper-medium"
  language: "vi"
  task: "transcribe"
  quantization:
    load_in_4bit: true
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: "nf4"
  device: "cuda"

lora:
  r: 16
  lora_alpha: 32
  target_modules: ["q_proj", "v_proj"]
  lora_dropout: 0.05
  bias: "none"

dataset:
  name: "nguyendv02/ViMD_Dataset"
  cache_dir: "./cache"
  sampling_rate: 16000
  regions: ["All", "Central", "South", "North"]

training:
  output_dir: "./logs/phowhisper-medium-{region}-vi"
  eval_output_dir: "./outputs/phowhisper-medium-{region}-vi"
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2
  learning_rate: 1e-5
  warmup_steps: 50
  save_steps: 50
  save_total_limit: 3
  logging_steps: 50
  fp16: false
  bf16: true
  optim: "paged_adamw_8bit"
  eval_strategy: "steps"
  eval_steps: 50
  per_device_eval_batch_size: 1
  metric_for_best_model: "wer"
  greater_is_better: false
  load_best_model_at_end: true
  save_strategy: "steps"
  hub_model_id: "minhtien2405/phowhisper-medium-{region}-vi"

eval:
  compute_metrics: true
  eval_on_train: false
  eval_on_test: true
  eval_on_dev: true
  eval_on_all: false
  eval_on_all_regions: true
  regions: ["All", "Central", "South", "North"]
  region: "{region}"
  test_split: "test"
  dev_split: "dev"
  train_split: "train"
  all_split: "all"

wandb:
  project: "PhoWhisper_ViMD"
  run_name: "phowhisper_finetune_{region}"

logging:
  log_dir: "./logs"
  log_file: "phowhisper_medium_vi_{region}_v0.log"
